name: ftzone
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.7+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: any
  flutter_bloc: ^4.0.0 #3.2.0
  rxdart: ^0.23.1 
  equatable: ^1.1.1
  flutter_launcher_icons: ^0.7.3
  package_info: ^0.4.0+17
  firebase_remote_config: ^0.3.0+3
  firebase_core: ^0.4.0  
  cloud_firestore: ^0.12.5
  ota_update: ^2.2.1
  font_awesome_flutter:
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.4+8
  responsive_screen: ^1.0.0
  flutter_spinkit: ^4.1.2  
  language_pickers: ^0.2.0+1 
  geolocator: ^5.3.1
  map_controller: ^0.7.1
  flutter_custom_clippers: ^1.1.1
  numberpicker: ^ 1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"
  adaptive_icon_background: "assets/launcher/ic_background.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - locale/i18n_en.json
    - locale/i18n_fr.json


  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Medium.ttf
